# https://github.com/pascalgn/automerge-action

name: automerge
on:
  # TODO I'm not sure why this section added. Maybe for
  #   triggering auto-merge on additional conflicts fix or
  #   something similar
  #
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    if: ${{ startsWith(github.event.pull_request.head.ref, 'release/') && github.event.pull_request.base.ref == 'prod' }}
    runs-on: ubuntu-latest
    steps:
      # We decide to turn this off for 'dev'
      #
      #      - id: automerge-dev
      #        name: automerge-dev
      #        if: ${{ startsWith(github.event.pull_request.head.ref, 'FE-') && github.event.pull_request.base.ref == 'dev' }}
      #        uses: "pascalgn/automerge-action@v0.15.3"
      #        env:
      #          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #          MERGE_DELETE_BRANCH: true
      #          # for cases when we merge prod to dev
      #          MERGE_DELETE_BRANCH_FILTER: "prod"
      #          MERGE_LABELS: ""
      #          MERGE_METHOD: "squash"
      - id: automerge-prod
        name: automerge-prod
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_DELETE_BRANCH: true
          MERGE_LABELS: ""
          MERGE_METHOD: "merge"
  sync:
    runs-on: ubuntu-latest
    needs:   automerge
    steps:
      - id: sync-dev-with-prod
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: prod
          title: 'Sync dev with prod'
          labels: |
            automated PR
